# Generated by Django 5.2.9 on 2025-12-22 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='published_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='views',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated', max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('tutorial', 'Tutorial'), ('analysis', 'Analysis'), ('tools', 'Tools'), ('case-study', 'Case Study'), ('trends', 'Trends')], max_length=50),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('dashboard', 'Dashboard'), ('analysis', 'Data Analysis'), ('visualization', 'Data Visualization'), ('machine-learning', 'Machine Learning'), ('business-intelligence', 'Business Intelligence')], max_length=50)),
                ('tools', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('live_link', models.URLField(blank=True)),
                ('code_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
