# Generated by Django 5.2.9 on 2025-12-22 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_blogpost_published_date_blogpost_views_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_title', models.CharField(default='My Data Portfolio', max_length=100)),
                ('portfolio_description', models.TextField(default='Welcome to my data analysis portfolio.', max_length=500)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('github_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('theme_color', models.CharField(choices=[('#4361ee', 'Blue'), ('#3a0ca3', 'Purple'), ('#f72585', 'Pink'), ('#06d6a0', 'Teal'), ('#1a1a2e', 'Dark Navy')], default='#4361ee', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
