# Generated by Django 5.2.9 on 2025-12-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_portfoliosettings_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated', max_length=500),
        ),
    ]
