# Generated by Django 5.2.9 on 2025-12-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_portfoliosettings_bio_portfoliosettings_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliosettings',
            name='portfolio_description',
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='portfolio_title',
            field=models.CharField(default='My Portfolio', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='theme_color',
            field=models.CharField(choices=[('#4361ee', 'Blue'), ('#3a0ca3', 'Purple'), ('#f72585', 'Pink'), ('#06d6a0', 'Teal'), ('#1a1a2e', 'Navy')], default='#4361ee', max_length=7),
        ),
    ]
