# Generated by Django 5.2.9 on 2025-12-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_experience_options_portfoliosettings_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliosettings',
            name='portfolio_title',
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='professional_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.CharField(blank=True, help_text='Comma-separated', max_length=500),
        ),
    ]
