# Generated by Django 5.2.9 on 2025-12-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_portfoliosettings_portfolio_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosettings',
            name='skills',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
